#!/bin/bash

cp pacman-chroot.conf /etc/pacman.conf

pacman-key --populate archlinux

pacman -Syu --noconfirm

pacman -S xorg xorg-apps xorg-xinit xorg-twm xterm xorg-xclock xfce4 xfce4-goodies network-manager-applet lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings light-locker accountsservice pulseaudio pavucontrol --noconfirm
pacman -S xf86-video-intel telegram-desktop chromium firefox gnu-free-fonts ttf-hack ttf-inconsolata gnome-font-viewer vlc gufw leafpad --noconfirm
systemctl enable lightdm.service

nombre_usuario=$(cat /etc/passwd | grep '/home' | cut -d: -f1) 
programaur="google-chrome"
cd /home/$nombre_usuario
git clone https://aur.archlinux.org/$programaur.git
chown -R $nombre_usuario:users /home/$nombre_usuario/$programaur
chown -R $nombre_usuario:users /home/$nombre_usuario/$programaur/PKGBUILD
cd /home/$nombre_usuario/$programaur
sudo -u $nombre_usuario makepkg -smp PKGBUILD --noconfirm
pacman -U *.pkg.tar.xz --noconfirm
rm -Rf /home/$nombre_usuario/$programaur
cd

wifinet=$(netctl list | awk -F " " '{print $2}')
netctl netctl disable $wifinet

read -p "Presiona ENTER para continuar..."

localectl set-x11-keymap latam

read -p "Presiona ENTER para reiniciar..."

reboot