#!/bin/sh
: 'Copyright (C) 2019 Código Cristo'
#!/bin/bash

#Colores
clear
red='\033[38;2;255;0;02m'
echo ""
echo ""
echo -e $red ">-------------------------------------------------------------------------<";
echo -e $red ">                                                                         <";
echo -e $red ">                                                                         <";
echo -e $red ">                      ██   █▄▄▄▄ ▄█▄    █▄▄▄▄ ▄█    ▄▄▄▄▄                <";
echo -e $red ">                      █ █  █  ▄▀ █▀ ▀▄  █  ▄▀ ██   █     ▀▄              <";
echo -e $red ">                      █▄▄█ █▀▀▌  █   ▀  █▀▀▌  ██ ▄  ▀▀▀▀▄                <";
echo -e $red ">                      █  █ █  █  █▄  ▄▀ █  █  ▐█  ▀▄▄▄▄▀                 <";
echo -e $red ">                         █   █   ▀███▀    █    ▐                         <";
echo -e $red ">                        █   ▀            ▀                               <";
echo -e $red ">                       ▀                                                 <";
echo -e $red ">                                                                         <";
function ProgressBar {
# Process data
    let _progress=(${1}*100/${2}*100)/100
    let _done=(${_progress}*6)/10
    let _left=60-$_done
# Build progressbar string lengths
    _fill=$(printf "%${_done}s")
    _empty=$(printf "%${_left}s")

# 1.2 Build progressbar strings and print the ProgressBar line
# 1.2.1 Output example:                           
# 1.2.1.1 Progress : [########################################] 100%
printf "\r > Cargando : |${_fill// /▇}${_empty// /-}| ${_progress}%%"

}

# Variables
_start=1

# This accounts as the "totalState" variable for the ProgressBar function
_end=100

# Proof of concept
for number in $(seq ${_start} ${_end})
do
    sleep 0.06
    ProgressBar ${number} ${_end}
done


#Poniendo el sistema en español
echo ""
echo ""
echo ""

cp .dialogrc /root

chmod +x *

echo es_ES.UTF-8 UTF-8 > /etc/locale.gen
locale-gen

echo LANG=es_ES.UTF-8 > /etc/locale.conf
export LANG=es_ES.UTF-8
echo ""
echo -e '\033[m'
sleep 3

#terminus-font
#FONT=ter-v14b  /etc/vconsole.conf 
#partprobe

#Inicio
dialog --backtitle "Instalación de ArchLinux - https://t.me/ArchLinuxCristo" \
--column-separator "|" --no-tags --title "| Código Cristo |" --ok-label 'Seleccionar' --no-cancel --menu "\nInstalador rápido de Arch Linux\n " 14 55 20 \
1 ' > | Instalar | Arch Linux| <' \
2 ' > | Instalar | Arch con Cifrado| <' \
3 ' > | Dual Boot | Windows Instalado| <' \
4 ' > | Dual Boot | GNU/Linux Instalado| <' \
5 ' > | GRUB | Recuperar Arranque de Sistema| <' 2>temp

#Opciones
if [ "$?" = "0" ]
then
        menu_inicio_return=$(cat temp)
 
# opción 1 - instalar solo
        if [ "$menu_inicio_return" = "1" ]
        then

        sh instalar_arch

fi

# opción 2 - Dual Boot - Windows Instalado
        if [ "$menu_inicio_return" = "2" ]
        then

        sh dual_windows

fi

# opción 3 - Dual Boot - LINUX
        if [ "$menu_inicio_return" = "3" ]
        then

        sh dual_windows

fi 


# opción 4 - Dual Boot - LINUX
        if [ "$menu_inicio_return" = "4" ]
        then

        sh dual_linux

fi 



# opción 5 - Dual Boot - LINUX
        if [ "$menu_inicio_return" = "5" ]
        then

        sh grub_recu

fi 

# Cancelar
else

    dialog --backtitle "| Instalación de ArchLinux - https://t.me/ArchLinuxCristo |" --stdout --ok-label 'Reiniciar' --title "| Finalizar |" --msgbox "\n| Comunidad para ayudar: t.me/ArchLinuxCristo |" 7 51

fi