#!/bin/sh
: 'Copyright (C) 2019 Código Cristo'
#!/bin/bash

# @Bourne_Again
# wget is.gd/arcris && sh arcris
# https://is.gd/stats.php?url=arcris

#Colores
clear
pacman -Sy git dialog ntp wget curl --noconfirm --needed
clear
rm arcris
git clone https://github.com/CodigoCristo/arcris
cd arcris
cp .dialogrc /root
chmod +x *
sleep 2
clear
sh arcris-install
