#!/bin/bash
clear
git clone https://github.com/CodigoCristo/arcris
cd arcris/

chmod +777 Arcris
chmod +777 arcris-up

clear
for i in $(seq 1 100)
do
    sleep 0.1 
    echo $i
done | dialog --title ' Hecho por Codigo Cristo ' --gauge "\nVisite la comunidad >> t.me/ArchLinuxCristo <<\n " 9 60 0

cp .dialogrc ~/.dialogrc
cp Arcris /bin/arcris
cp arcris-up /bin/arcris-up

cd ..
rm -r arcris
clear
arcris
