#!/bin/sh
: 'Copyright (C) 2019 Código Cristo'
#!/bin/bash

# @Bourne_Again
# wget is.gd/arcris && sh arcris
# https://is.gd/stats.php?url=arcris

#Colores
clear
pacman -Sy glibc dialog curl --noconfirm --needed
#clear
#rm arcris
#git clone https://github.com/CodigoCristo/arcris
#cd arcris


#pacman -Sy dialog --noconfirm --needed
#curl -LJO https://github.com/Vertecedoc4545/arcris/tree/master/soms/arcris-xonad.tar.xz
#tar  -xJf  arcris-xmonad.tar.xz
cd arcris-xmonad

cp .dialogrc /root
chmod +x *
sleep 2
clear
sh arcris-install
