#!/bin/bash
clear
git clone https://github.com/CodigoCristo/arcris
cd arcris/
chmod +777 Arcris
chmod +777 arcris-up
clear
echo -e '\033[44;1m'
echo " CARGANDO... "
echo ""
for ((k = 0; k <= 10 ; k++))
do
    echo -n "[ "
    for ((i = 0 ; i <= k; i++)); do echo -n "###"; done
    for ((j = i ; j <= 10 ; j++)); do echo -n "   "; done
    v=$((k * 10))
    echo -n " ] "
    echo -n "$v %" $'\r'
    sleep 0.1
done
printf "\n\n Hecho por Codigo Cristo! \n"
echo ""
echo -e ' https://github.com/CodigoCristo \033[m'
echo ""

cp .dialogrc ~/.dialogrc
cp Arcris /bin/arcris
cp arcris-up /bin/arcris-up

cd ..
rm -r arcris
sleep 2
clear
arcris
