#!/bin/bash


cp pacman.conf /etc/pacman.conf

pacman-key --populate archlinux

pacman -Syu --noconfirm

reflector --verbose --latest 5 --sort rate --save /etc/pacman.d/mirrorlist

pacman -S xorg xorg-apps xorg-xinit xorg-twm xterm xorg-xclock xfce4 xfce4-goodies network-manager-applet lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings light-locker accountsservice pulseaudio pavucontrol amd-ucode --noconfirm

pacman -S xf86-video-ati mesa lib32-mesa mesa-vdpau libva-mesa-driver lib32-mesa-vdpau lib32-libva-mesa-driver libva-vdpau-driver libvdpau-va-gl libva-utils vdpauinfo opencl-mesa clinfo ocl-icd lib32-ocl-icd opencl-headers --noconfirm

pacman -S code telegram-desktop chromium firefox gnu-free-fonts ttf-hack ttf-inconsolata gnome-font-viewer vlc gufw leafpad --noconfirm

systemctl enable lightdm

read -p "Presiona ENTER para continuar..."

localectl set-x11-keymap latam

read -p "Presiona ENTER para reiniciar..."

reboot



