#!/bin/bash


cmd=(dialog --keep-tite --backtitle "${title}" \
--no-collapse --cr-wrap --column-separator "|" --no-tags --ok-label '  Seleccionar  ' --menu "\nSelecciona tu gestor de ventana a instalar - (WM)\n " 14 60 14)

options=(1 "> i3wm | Disponible <"
         2 "> bspwm | Disponible <"
         3 "> dwm | Disponible <"
         3 "> awesome | Disponible <"
         3 "> openbox | Disponible <")


choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)