#!/bin/bash


cmd=(dialog --no-collapse --cr-wrap --backtitle "${title}"  --title "-| AUR Helper |-" \
--no-tags  --ok-label ' Confirmar ' --cancel-label ' No deseo esto ' --column-separator "|" --checklist "\n[ ESPACIO ] - Para marcar o desmarcar *\n " 19 80 19)
options=(1 "yay | Terminal" on
         2 "trizen | Terminal" off
         3 "pikaur | Terminal" off
         4 "aurman | Terminal" off
         5 "pakku | Terminal" off
         6 "Pamac | Graphical" off
         7 "Octopi | Graphical" off
         8 "Cylon | Graphical" off
         9 "Argon | Graphical" off
         10 "Pakku GUI | Graphical" off)

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in
        1)
            RS1=true
            ;;
        2)
            RS2=true
            ;;
        3)
            RS3=true
            ;;
        4)
            RS4=true
            ;;    
        5)
            RS5=true
            ;;            
        6)
            RS6=true
            ;;

        7)
            RS7=true
            ;;         

    esac
done
#FINAL DE Redes Sociales