#!/bin/bash
proximamente () {
    dialog --backtitle "${title}" --title "-| Código Cristo |-" --stdout --ok-label "${btn_accept}" --msgbox "${msg_coming}" 7 55
}


disksystem () {

GRUBINSTALL=1

cmd=(dialog --no-collapse --cr-wrap --backtitle "${title}" --title "${title_disk}" \
--ok-label "${btn_confirm}" --menu "${msg_menu_disk}" 15 60 15)
options=(1 "${msg_menu_disk1}"   
         2 "${msg_menu_disk2}"
         3 "${msg_menu_disk3}"
         4 "${msg_menu_disk4}"
         5 "${msg_menu_disk5}"
         6 "${msg_menu_disk6}")

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in
    ################

1) ################ 
source lib/partition/autopartition
autopartition
;;

2) ################
source lib/partition/encryptpartition
# GRUBINSTALL=2
# encryptpartition
proximamente
;;
3) ################
source lib/partition/manualpartition
# manualpartition
manualpartition
;;

4) ################
source lib/partition/dualbootpartition
GRUBINSTALL=3
dualpartition
;;


5) ################
source lib/partition/tabledisk
tabledisk
;;


6) ################
source lib/partition/deletediskdd
deletediskdd
;;

    esac
done

sectiondisk=1

}


