#!/bin/bash

environment () {

DE=""
DM=""
WM=""
seleccionDE=false
seleccionWM=false
seleccionXORG=false
seleccionTTY=false



cmd=(dialog --keep-tite --no-collapse --cr-wrap --backtitle "${title}" --title "-| Entorno |-" --column-separator "|" --no-tags --ok-label '< Seleccionar >' --nocancel --menu "\nElige una opción\n " 12 50 12)

options=(3 "Emulador de Terminal | (tty)"
         1 "Entorno de escritorio | (DE)"
         2 "Gestor de ventanas | (WM)")

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)

for choice in $choices
do
    case $choice in
        1) #INICIO (DE)    

seleccionDE=true

cmd=(dialog --keep-tite --no-collapse --cr-wrap --backtitle "${title}" --column-separator "|" --no-tags --ok-label '< Seleccionar >' --menu "\nSelecciona tu escritorio a instalar - (DE)\n " 21 60 21)

options=(1 " > | xfce4 | Xfce desktop| <"
         2 " > | gnome | GNOME Classic desktop| <"
         3 " > | plasma | KDE Plasma desktop| <"
         4 " > | deepin | Deepin desktop| <"
         5 " > | mate | Mate GTK3 desktop| <"
         6 " > | lxqt | LXDE-Qt & Razor-qt projects| <"
         7 " > | lxde | The Lightweight X11 GTK2| <"
         8 " > | lxde-gtk3 | The Lightweight X11 GTK3| <"
         9 " > | budgie-desktop | Budgie desktop| <"
         10 " > | cinnamon | Cinnamon desktop| <"
         11 " > | gnome-flashback | GNOME 2 desktop| <"
         12 " > | enlightenment | Enlightenment desktop| <")

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)

for choice in $choices
do
    case $choice in
        
###########SELECCION (DE)
        1) #XFCE4

cmd=(dialog --keep-tite --backtitle "${title}" \
--no-collapse --cr-wrap --column-separator "|" --no-tags \
--ok-label '< Seleccionar >' --nocancel --menu "\n\
Selecciona una opción para XFCE4 \n " 12 60 20)

options=(1 "   Xfce4                    "
         2 "   Xfce4 - Tema Arcris      ")

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)

for choice in $choices
do
    case $choice in

        1)  DE="Xfce4"
            ;;
            
        2)  DE="Xfce4 Arcris"
            ;;
            
    esac
done
        ;;


        2)  #INICIO GNOME
cmd=(dialog --keep-tite --backtitle "${title}" \
--no-collapse --cr-wrap --column-separator "|" --no-tags \
--ok-label '< Seleccionar >' --nocancel --menu "\n \
Selecciona una opción para GNOME \n " 12 60 20)

options=(1 "   Gnome || Sistema Completo  "
         2 "   Gnome || Minimalista       ")

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)

for choice in $choices
do
    case $choice in

        1)  DE="Gnome"
            ;;
            
        2)  DE="Gnome Lite"
            ;;

    esac
done
            ;;
 
        3)  #INICIO KDE
cmd=(dialog --keep-tite --backtitle "${title}" \
--no-collapse --cr-wrap --column-separator "|" --no-tags \
--ok-label '< Seleccionar >' --nocancel --menu "\n \
Selecciona una opción para KDE Plasma \n " 12 60 20)

options=(1 "   Plasma || Sistema Completo  "
         2 "   Plasma || Minimalista       ")

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)

for choice in $choices
do
    case $choice in

        1)  DE="KDE Plasma"
            ;;
            
        2)  DE="KDE Plasma Lite"
            ;;

    esac
done
            ;;


        4)  #INICIO DEEPIN
            DE="Deepin"
            ;;

        5)  #INICIO MATE
            DE="MATE"
            ;;

        6)  #INICIO LXQt
            DE="LXQt"
            ;;

        7)  #INICIO LXDE
            DE="LXDE"
            ;;

        8)  #INICIO LXDE GTK3
            DE="LXDE GTK3"
            ;;

        9)  #INICIO Budgie
            DE="Budgie"
            ;;

        10)  #INICIO Cinnamon
            DE="Cinnamon"
            ;;

        11)  #INICIO GNOME 2
            DE="GNOME 2"
            ;;

        12)  #INICIO Enlightenment
            DE="Enlightenment"
            ;;


    esac
done
            ;;
#########FIN ESCRITORIO


        2) #INICIO (WM)
seleccionWM=true

cmd=(dialog --keep-tite --backtitle "${title}" \
--no-collapse --cr-wrap --column-separator "|" --no-tags --ok-label '  Seleccionar  ' --menu "\nSelecciona tu gestor de ventana a instalar - (WM)\n " 14 60 14)

options=(1 "> i3wm | Disponible <"
         2 "> bspwm | Disponible <"
         3 "> dwm | Disponible <"
         4 "> awesome | Disponible <"
         5 "> openbox | Disponible <")

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)

for choice in $choices
do
    case $choice in
        1)  
            WM="i3wm"
            ;;

        2)
            WM="bspwm"
            ;;

        3)
            WM="dwm"
            ;;

        4)
            WM="awesome"
            ;;

        5)
            WM="openbox"
            ;;
    esac
done
#FINAL (WM)
            ;;
            

        3)
          seleccionTTY=true
          tty="tty"
          ;;


    esac
done

sectionenv=1

}






installenvironment () {


case $environment in 

  "tty")
  echo "" 
  echo "Se esta instalando el entorno TTY:" 
  echo "" 
  arch-chroot /mnt /bin/bash -c "pacman -Syu --noconfirm"

  ;;

  "Xfce4 Arcris")
  echo "" 
  echo "Se esta instalando el entorno Xfce4:" 
  echo "" 

  arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-server --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S xfce4 --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S xfce4-goodies --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S network-manager-applet --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lightdm --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lightdm-gtk-greeter --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lightdm-gtk-greeter-settings --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S light-locker --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S accountsservice --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S mugshot --noeditmenu --noconfirm --needed"
 
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnu-free-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-hack --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-inconsolata --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-font-awesome --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S awesome-terminal-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S noto-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S noto-fonts-emoji --noeditmenu --noconfirm --needed"
  
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ffmpegthumbs --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ffmpegthumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S freetype2 --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S poppler-glib --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libgsf --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S raw-thumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libgsf --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "systemctl enable lightdm"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S plata-theme-bin --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S papirus-icon-theme --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gtk-engine-murrine --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-roboto --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S pavucontrol --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gedit --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gedit-plugins --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S plank --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S plank-theme-namor --noeditmenu --noconfirm --needed"

arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S android-file-transfer android-tools android-udev msmtp libmtp libcddb gvfs gvfs-afc gvfs-smb gvfs-gphoto2 gvfs-mtp gvfs-goa gvfs-nfs gvfs-google gst-libav dosfstools f2fs-tools ntfs-3g udftools nilfs-utils polkit gpart mtools cifs-utils --noeditmenu --noconfirm --needed"
  
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S wget unzip zip --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "wget https://raw.githubusercontent.com/CodigoCristo/themexfce4/master/configxfce4.zip"
  arch-chroot /mnt /bin/bash -c "rm -r /home/$username/.config"
  arch-chroot /mnt /bin/bash -c "unzip configxfce4.zip -d /home/$username/.config"
  arch-chroot /mnt /bin/bash -c "chown -R $username:users /home/$username/.config/"


# Comprimir un directorio
# zip sampleZipFile.zip /sampleZip/ExampleDir

# para sobreescribir archivos
# unzip -o sampleZipFile.zip 

# Descomprimir un archivo a un directorio diferente
# unzip sampleZipFile.zip -d /usr/sampleZip/ExampleDir

  ;;


  "Xfce4")
  echo "" 
  echo "Se esta instalando el entorno Xfce4:" 
  echo "" 

  arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-server --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S xfce4 --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S xfce4-goodies --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S network-manager-applet --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lightdm --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lightdm-gtk-greeter --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lightdm-gtk-greeter-settings --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S light-locker --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S accountsservice --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S mugshot --noeditmenu --noconfirm --needed"
 
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnu-free-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-hack --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-inconsolata --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-font-awesome --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S awesome-terminal-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S noto-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S noto-fonts-emoji --noeditmenu --noconfirm --needed"
  
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ffmpegthumbs --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ffmpegthumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S freetype2 --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S poppler-glib --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libgsf --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S raw-thumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libgsf --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "systemctl enable lightdm"

  ;;



  "Gnome")
  echo "" 
  echo "Se esta instalando el entorno Gnome:" 
  echo "" 

  arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-server --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnome  --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnome-extra --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnome-shell --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnome-shell-extensions --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gdm --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S chrome-gnome-shell --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S webp-pixbuf-loader --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnome-tweaks --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnu-free-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-hack --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-inconsolata --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-font-awesome --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S awesome-terminal-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S noto-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S noto-fonts-emoji --noeditmenu --noconfirm --needed"
  
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S tumbler --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ffmpegthumbs --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ffmpegthumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S freetype2 --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S poppler-glib --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libgsf --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S raw-thumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libgsf --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "systemctl enable gdm"

  ;;


  "Gnome Lite")
  echo "" 
  echo "Se esta instalando el entorno Gnome:" 
  echo "" 

  arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-server --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnome-shell --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gdm --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnome-control-center --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnome-tweaks --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnome-terminal --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S nautilus --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnu-free-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-hack --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-inconsolata --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-font-awesome --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S awesome-terminal-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S noto-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S noto-fonts-emoji --noeditmenu --noconfirm --needed"
  
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ffmpegthumbs --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ffmpegthumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S freetype2 --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S poppler-glib --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libgsf --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S raw-thumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libgsf --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "systemctl enable gdm"

  ;;


  "KDE Plasma")
  echo "" 
  echo "Se esta instalando el entorno KDE Plasma:" 
  echo "" 

  arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-server --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S plasma --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S kde-applications --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S konsole --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S konqueror --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S dolphin --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S discover --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S latte-dock --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S bluedevil --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S kate --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S kdialog --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S keditbookmarks --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S kwrite --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S appmenu-gtk-module --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libdbusmenu-glib --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libdbusmenu-gtk3 --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libdbusmenu-gtk2 --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S kfind --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S khelpcenter --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S kscreen --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S powerdevil --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S kdeconnect --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S kdegraphics-thumbnailers --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S sddm --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libxcb --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S qt5-virtualkeyboard --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnu-free-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-hack --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-inconsolata --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-font-awesome --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S awesome-terminal-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S noto-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S noto-fonts-emoji --noeditmenu --noconfirm --needed"
  
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ffmpegthumbs --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ffmpegthumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S freetype2 --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S poppler-glib --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libgsf --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S raw-thumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libgsf --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "systemctl enable sddm"

  ;;


"KDE Plasma Lite")
  echo "" 
  echo "Se esta instalando el entorno KDE Plasma:" 
  echo "" 

  arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-server --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S plasma --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S dolphin --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S konsole --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S discover --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S sddm --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libxcb --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S qt5-virtualkeyboard --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnu-free-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-hack --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-inconsolata --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-font-awesome --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S awesome-terminal-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S noto-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S noto-fonts-emoji --noeditmenu --noconfirm --needed"
  
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ffmpegthumbs --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ffmpegthumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S freetype2 --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S poppler-glib --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libgsf --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S raw-thumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libgsf --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "systemctl enable sddm"

  ;;



"Deepin")
  echo "" 
  echo "Se esta instalando el entorno Deepin:" 
  echo "" 

  arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-server --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S deepin --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S deepin-extra --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lightdm  --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lightdm-gtk-greeter  --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lightdm-gtk-greeter-settings  --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S light-locker  --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S accountsservice --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnu-free-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-hack --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-inconsolata --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-font-awesome --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S awesome-terminal-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S noto-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S noto-fonts-emoji --noeditmenu --noconfirm --needed"
  
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ffmpegthumbs --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ffmpegthumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S freetype2 --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S poppler-glib --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libgsf --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S raw-thumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libgsf --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "systemctl enable lightdm.service"

  ;;


"MATE")
  echo "" 
  echo "Se esta instalando el entorno MATE:" 
  echo "" 

  arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-server --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S mate --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S mate-extra --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S mate-applet-dock --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S mate-menu --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S brisk-menu --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libcanberra --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S mate-power-manager --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S mate-media --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S network-manager-applet --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S system-config-printer --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lightdm --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lightdm-gtk-greeter --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lightdm-gtk-greeter-settings --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S light-locker --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S accountsservice --noeditmenu --noconfirm --needed"
  
  arch-chroot /mnt /bin/bash -c "systemctl enable lightdm"

  ;;


"LXQt")
  echo "" 
  echo "Se esta instalando el entorno LXQt:" 
  echo "" 

  arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-server --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lxqt --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S papirus-icon-theme --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S arc-gtk-theme --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S xscreensaver --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S connman --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lxqt-connman-applet --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S connman-gtk --noeditmenu --noconfirm --needed"
  
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S sddm --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S light-locker --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S accountsservice --noeditmenu --noconfirm --needed"
  
  arch-chroot /mnt /bin/bash -c "systemctl enable sddm"
  arch-chroot /mnt /bin/bash -c "systemctl enable connman"
  arch-chroot /mnt /bin/bash -c "systemctl disable NetworkManager"

  ;;



"LXDE")
  echo "" 
  echo "Se esta instalando el entorno LXDE:" 
  echo "" 

  arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-server --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lxde --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lxmed --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S slock --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lxdm --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S accountsservice --noeditmenu --noconfirm --needed"
  
  arch-chroot /mnt /bin/bash -c "systemctl enable lxdm"

  ;;



"LXDE GTK3")
  echo "" 
  echo "Se esta instalando el entorno LXDE GTK3:" 
  echo "" 

  arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-server --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lxde-gtk3 --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S slock --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lxdm --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S accountsservice --noeditmenu --noconfirm --needed"
  
  arch-chroot /mnt /bin/bash -c "systemctl enable lxdm"

  ;;



"Budgie")
  echo "" 
  echo "Se esta instalando el entorno Budgie:" 
  echo "" 

  arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-server --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S budgie-desktop --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S budgie-screensaver --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnome-control-center --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnome-tweaks --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S tilix --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S nautilus --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnu-free-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-hack --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-inconsolata --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-font-awesome --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S awesome-terminal-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S noto-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S noto-fonts-emoji --noeditmenu --noconfirm --needed"
  
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lightdm --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lightdm-gtk-greeter --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lightdm-gtk-greeter-settings --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S light-locker --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S accountsservice --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "systemctl enable lightdm"

  ;;


"Cinnamon")
  echo "" 
  echo "Se esta instalando el entorno Cinnamon:" 
  echo "" 

  arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-server --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S cinnamon --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S slock --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S cinnamon-translations --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lxterminal --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnu-free-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-hack --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-inconsolata --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-font-awesome --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S awesome-terminal-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S noto-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S noto-fonts-emoji --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lightdm --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S numlockx --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lightdm-slick-greeter --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S light-locker --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S accountsservice --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "systemctl enable lightdm"

clear
echo ""
touch /mnt/etc/lightdm/slick-greeter.conf
tee /mnt/etc/lightdm/slick-greeter.conf <<EOF
[Greeter]
background=/usr/share/backgrounds/arcris.png
stretch-background-across-monitors=true
show-hostname=false
show-a11y=false
show-power=false
activate-numlock=true
background-color=#0000
draw-user-backgrounds=true
icon-theme-name=Adwaita
EOF

sed -i 's/#greeter-session=example-gtk-gnome/greeter-session=lightdm-slick-greeter/g' /mnt/etc/lightdm/lightdm.conf





  ;;



"GNOME 2")
  echo "" 
  echo "Se esta instalando el entorno GNOME 2:" 
  echo "" 

  arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-server --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnome-flashback --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnome-backgrounds --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnome-control-center --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S network-manager-applet --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnome-applets --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S sensors-applet --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S metacity --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnome-control-center --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnome-tweaks --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lxterminal --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S nautilus --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnu-free-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-hack --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-inconsolata --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-font-awesome --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S awesome-terminal-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S noto-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S noto-fonts-emoji --noeditmenu --noconfirm --needed"
  
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lightdm --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lightdm-gtk-greeter --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lightdm-gtk-greeter-settings --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S light-locker --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S accountsservice --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "systemctl enable lightdm"

  ;;



"Enlightenment")
  echo "" 
  echo "Se esta instalando el entorno Enlightenment:" 
  echo "" 

  arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-server --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S enlightenment --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S entrance-git --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S terminology --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S network-manager-applet --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S eluminance-git --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S stalonetray --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lxterminal --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnu-free-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-hack --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-inconsolata --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-font-awesome --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S awesome-terminal-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S noto-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S noto-fonts-emoji --noeditmenu --noconfirm --needed"
  
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S accountsservice --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "systemctl enable entrance"

  ;;


"i3wm")
  echo "" 
  echo "Se esta instalando el entorno i3wm:" 
  echo "" 

  arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-server --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S i3-gaps --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S i3blocks --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S i3lock --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S i3status --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S dmenu --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S rofi --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S st --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S rxvt-unicode --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ly --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S pcmanfm --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S tumbler --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ffmpegthumbs --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ffmpegthumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S raw-thumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S freetype2 --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S network-manager-applet --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S polkit-gnome --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnome-keyring  --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-hack --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnu-free-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S awesome-terminal-fonts --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S papirus-icon-theme --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnome-themes-extra --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lxappearance --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S feh --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S xclip --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S maim --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S accountsservice --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "systemctl enable ly"

  ;;



"bspwm")
  echo "" 
  echo "Se esta instalando el entorno bspwm:" 
  echo "" 

  arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-server --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S bspwm --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S sxhkd --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S dmenu --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S rofi --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S st --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S rxvt-unicode --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ly --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S pcmanfm --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S tumbler --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ffmpegthumbs --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ffmpegthumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S raw-thumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S freetype2 --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S network-manager-applet --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S polkit-gnome --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnome-keyring  --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-hack --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnu-free-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S awesome-terminal-fonts --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S papirus-icon-theme --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnome-themes-extra --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lxappearance --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S feh --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S xclip --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S maim --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S accountsservice --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "systemctl enable ly"
  
  ;;


"dwm")
  echo "" 
  echo "Se esta instalando el entorno dwm:" 
  echo "" 

  arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-server --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S dwm-git --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S dmenu --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S rofi --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S st --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S rxvt-unicode --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ly --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S pcmanfm --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S tumbler --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ffmpegthumbs --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ffmpegthumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S raw-thumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S freetype2 --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S network-manager-applet --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S polkit-gnome --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnome-keyring  --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-hack --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnu-free-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S awesome-terminal-fonts --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S papirus-icon-theme --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnome-themes-extra --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lxappearance --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S feh --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S xclip --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S maim --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S accountsservice --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "systemctl enable ly"
  
  ;;



"awesome")
  echo "" 
  echo "Se esta instalando el entorno Awesome:" 
  echo "" 

  arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-server --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S awesome --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S dmenu --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S rofi --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S st --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S rxvt-unicode --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ly --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S pcmanfm --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S tumbler --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ffmpegthumbs --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ffmpegthumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S raw-thumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S freetype2 --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S network-manager-applet --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S polkit-gnome --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnome-keyring  --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-hack --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnu-free-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S awesome-terminal-fonts --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S papirus-icon-theme --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnome-themes-extra --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lxappearance --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S feh --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S xclip --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S maim --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S accountsservice --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "systemctl enable ly"
  
  ;;



"openbox")
  echo "" 
  echo "Se esta instalando el entorno Open box:" 
  echo "" 

  arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-server --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
  arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S openbox --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S obconf --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lxappearance-obconf --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lxinput --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lxrandr --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S obkey --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S obapps --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ob-autostart --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S dmenu --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S rofi --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S st --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S rxvt-unicode --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ly --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S pcmanfm --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S tumbler --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ffmpegthumbs --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ffmpegthumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S raw-thumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S freetype2 --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S network-manager-applet --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S polkit-gnome --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnome-keyring  --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-hack --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnu-free-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S awesome-terminal-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-dejavu --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-liberation --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S papirus-icon-theme --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnome-themes-extra --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lxappearance --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S feh --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S xclip --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S maim --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S accountsservice --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "systemctl enable ly"
  
  ;;




esac

}