#!/bin/bash

lang () {

cmd=(dialog --backtitle "${title}" --title "${title_langtty}" --no-cancel --keep-tite --menu "${msg_langtty}" 15 50 11)

options=(la-latin1  "Latino Americano"
         es     	  "Español"
         us     	  "Ingles"
         ru			    "Ruso"
         otros      "(+)Teclados")

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)

for choice in $choices
do
    case $choice in
        es)
            loadkeys es
      keyboard="es"
      loadkeys=$keyboard 
      keymap=$keyboard  
            ;;
            
        la-latin1)
            loadkeys la-latin1
      keyboard="la-latin1"
      loadkeys=$keyboard 
      keymap=$keyboard 
            ;;
            
        us)
            loadkeys us
      keyboard="us"
      loadkeys=$keyboard 
      keymap=$keyboard  
            ;;

        ru)
            loadkeys ru
      keyboard="ru"
      loadkeys=$keyboard 
      keymap=$keyboard  
            ;;
            
        otros)
            selected=0 
      while [ $selected == "0" ];do 
        localeskeymap="$(localectl list-keymaps | awk '$localeskeymap=$localeskeymap" Keymap"')" && localeskeymap=$(echo "$localeskeymap") 
        keyboard=$(dialog --backtitle "${title}" --clear --no-cancel --title "${title_langtty}" --menu " \n " 15 50 15   ${localeskeymap} 2>&1 > /dev/tty) 
        if [ $? == 0 ];then 
          loadkeys $keyboard 
          keymap=$keyboard 
          selected=1 
        else 
          dialog --backtitle "${title}" --title "${title_error}" --stdout --ok-label "${btn_confirm}" --msgbox "${msg_langerror}" 5 55 
        fi
      done
        ;;
    esac
done



###########################################


cmd=(dialog --backtitle "${title}" --title "${title_langXorg}" --no-cancel --keep-tite --menu "${msg_langXorg}" 15 50 11)

options=(latam  	"Latino Americano"
         es     	"Español"
         us     	"Ingles"
         ru			  "Ruso"
         otros    "(+)Teclados")

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)

for choice in $choices
do
    case $choice in
        es)
      keyboardx="es"
      keymapx=$keyboardx
            ;;
            
        latam)
      keyboardx="latam"
      keymapx=$keyboardx
            ;;
            
        us)
      keyboardx="us"
      keymapx=$keyboardx
            ;;
        
        ru)
      keyboardx="ru"
      keymapx=$keyboardx
            ;;


        otros)
            selected=0 
      while [ $selected == "0" ];do 
        localeskeymapx="$(cat lib/list_X11keymap | awk '$localeskeymapx=$localeskeymapx" x11-keymap-layout"')" && localeskeymapx=$(echo "$localeskeymapx") 
        keyboardx=$(dialog --backtitle "${title}" --clear --no-cancel --title "${title_langXorg}" --menu " \n " 15 50 15   ${localeskeymapx} 2>&1 > /dev/tty) 
        if [ $? == 0 ];then 
          keymapx=$keyboardx 
          selected=1 
        else 
          dialog --backtitle "${title}" --title "${title_error}" --stdout --ok-label "${btn_confirm}" --msgbox "${msg_langerror}" 5 55 
        fi
      done
        ;;
    esac
done

sectionlang=1

}